---
- hosts: localhost

  tasks:
  - name: ex4 step 1
    debug: 
      msg: "ex4 step 1 ..." 

  - name: ex4 step 2
    include: ex41.yml 

  - name: ex4 step 3
    debug: 
      msg: "ex4 step 3" 

