---
- hosts: localhost

  tasks:
  - name: get IP address
    shell: ip addr show enp1s0 | awk '/inet / {print $2}'  
    register: ip_address_result
  - name: display IP
    debug: 
      msg: "IP address of enp3s0 is {{ip_address_result.stdout}}"


